const Ddata = [
  {
    id: 7,
    cover: "./images/discount/desc1.jpg",
    name: "Monitor HP 19.5”",
    price: "250",
    cover1: "./images/discount/desc1.jpg",
    cover2: "./images/flash/yerba.png",
    desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
  },
  {
    id: 8,
    cover: "./images/discount/desc2.jpg",
    name: "Smart TV 32”",
    cover1: "./images/discount/desc2.jpg",
    cover2: "./images/flash/yerba.png",
    price: "450",
    desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
  },
  {
    id: 9,
    cover: "./images/discount/desc3.jpg",
    name: "Butacas",
    cover1: "./images/discount/desc3.jpg",
    cover2: "./images/flash/yerba.png",
    price: "50",
    desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
  },
  {
    id: 10,
    cover: "./images/discount/desc4.jpg",
    name: "Moto Triciclo",
    cover1: "./images/discount/desc4.jpg",
    cover2: "./images/flash/yerba.png",
    price: "100",
    desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
  },
  {
    id: 11,
    cover: "./images/discount/desc5.jpg",
    name: "Bicicleta Philco",
    cover1: "./images/discount/desc5.jpg",
    cover2: "./images/flash/yerba.png",
    price: "20",
    desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
  },
  {
    id: 12,
    cover: "./images/discount/desc6.jpg",
    name: "Bicicletas R12",
    cover1: "./images/discount/desc6.jpg",
    cover2: "./images/flash/yerba.png",
    price: "200",
    desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
  },
  {
    id: 13,
    cover: "./images/discount/desc7.jpg",
    name: "Cochecito",
    cover1: "./images/discount/desc7.jpg",
    cover2: "./images/flash/yerba.png",
    price: "300",
    desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
  },
  {
    id: 14,
    cover: "./images/discount/desc8.jpg",
    name: "Horno Eléctrico",
    cover1: "./images/discount/desc8.jpg",
    cover2: "./images/flash/yerba.png",
    price: "30",
    desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
  },
  {
    id: 15,
    cover: "./images/discount/desc0.jpg",
    name: "Secarropas",
    cover1: "./images/discount/desc9.jpg",
    cover2: "./images/flash/yerba.png",
    price: "80",
    desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
  },
];
export default Ddata;
