const Data = {
  productItems: [
    {
      id: 1,
      discount: 50,
      cover: "./images/flash/aaaa.png",
      cover1: "./images/flash/aaaa.png",
      cover2: "./images/flash/dulce2.png",
      name: "Productos libres de gluten",
      price: 100,
      desc: "El dulce de leche libre de gluten es realmente delicioso. Verdadero estilo artesanal, balanceado, increíble textura.Elaborado sin azúcar con materias primas de calidad superior que garantizan un producto excelente.",
    },
    {
      id: 2,
      discount: 40,
      cover: "./images/flash/b.png",
      name: "Jugos Naturales sin azúcar",
      price: 20,
      cover1: "./images/flash/b.png",
      cover2: "./images/flash/jugo.png",
      desc: "Jugos Naturales con Stevia Cuarto Creciente Presentación 1500 Cc. Los jugos naturales son la mejor opción para refrescar, nutrir y darle vitalidad a nuestro organismo. Cuarto Creciente cuenta con una amplia variedad de sabores frutales, endulzados con stevia, ideal para disfrutar con amigos y en familia. Se presentan en botellas de 500 cm3 y 1500 cm3, en varios sabores como naranja, manzana, kiwi, pera, frutos rojos, ciruela, maracuyá y arándanos siendo éste el más requerido por nuestros clientes.",
    },
    {
      id: 3,
      discount: 40,
      cover: "./images/flash/c.jpg",
      name: "Skip",
      cover1: "./images/flash/c.jpg",
      cover2: "./images/flash/skip.png",
      price: 200,
      desc: "Skip Para Diluir Jabón Líquido 500 Ml + Botella 3l Reutiliza",
    },
    {
      id: 4,
      discount: 40,
      cover: "./images/flash/d.jpg",
      name: "YERBAS ORGÁNICAS",
      cover1: "./images/flash/d.jpg",
      cover2: "./images/flash/yerba.png",
      price: 50,
      desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
    },
    {
      id: 5,
      discount: 50,
      cover: "./images/flash/f.jpg",
      name: "Premezla ",
      cover1: "./images/flash/f.jpg",
      cover2: "./images/flash/skip.png",
      price: 100,
      desc: "Premezcla Glutal Para Pan x 1 kg. Premezcla para elaborar panificados libre de gluten. Ingredientes: Almidón de maíz, harina de arroz, fécula de mandioca, azúcar, proteína de suero lácteo, cloruro de sodio.",
    },
    {
      id: 6,
      discount: 50,
      cover: "./images/flash/e.jpg",
      name: "Pack promo ala",
      price: 100,
      cover1: "./images/flash/e.jpg",
      cover2: "./images/flash/skip.png",
      desc: "El Lavado Perfecto con Ala es posible: remueve las manchas, cuida tu ropa,fragancia duradera y combate el mal olor. Mientras ahorra hasta un 20%* Es más ecológico gracias a que posee activos biodegradables y su botella está hecha con plástico reciclado. Por otro lado, su fórmula tiene Activos Biodegradables. Esto quiere decir que el residuo químico que queda en el agua tras haber realizado el lavado, particularmente hablando de los agentes de limpieza presentes en la fórmula del producto, se biodegradaran en el tiempo a un mínimo del 80%. Y por último, podrás conseguir el poder imbatible de Ala Líquido para diluir hasta un 20% de ahorro. Su fórmula tiene una tecnología contra el mal olor, esta eficiente tecnología encapsula los diferentes tipos de malos olores como el sudor, moho y hongos, humo y olores de baño. ",
    },
    {
      id: 7,
      discount: 50,
      cover: "./images/discount/desc1.jpg",
      name: "Monitor HP 19.5”",
      price: "250",
      cover1: "./images/discount/desc1.jpg",
      cover2: "./images/flash/yerba.png",
      desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
    },
    {
      id: 8,
      cover: "./images/discount/desc2.jpg",
      name: "Smart TV 32”",
      cover1: "./images/discount/desc2.jpg",
      cover2: "./images/flash/yerba.png",
      price: "450",
      desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
    },
    {
      id: 9,
      cover: "./images/discount/desc3.jpg",
      name: "Butacas",
      cover1: "./images/discount/desc3.jpg",
      cover2: "./images/flash/yerba.png",
      price: "50",
      desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
    },
    {
      id: 10,
      cover: "./images/discount/desc4.jpg",
      name: "Moto Triciclo",
      cover1: "./images/discount/desc4.jpg",
      cover2: "./images/flash/yerba.png",
      price: "100",
      desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
    },
    {
      id: 11,
      cover: "./images/discount/desc5.jpg",
      name: "Bicicleta Philco",
      cover1: "./images/discount/desc5.jpg",
      cover2: "./images/flash/yerba.png",
      price: "20",
      desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
    },
    {
      id: 12,
      cover: "./images/discount/desc6.jpg",
      name: "Bicicletas R12",
      cover1: "./images/discount/desc6.jpg",
      cover2: "./images/flash/yerba.png",
      price: "200",
      desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
    },
    {
      id: 13,
      cover: "./images/discount/desc7.jpg",
      name: "Cochecito",
      cover1: "./images/discount/desc7.jpg",
      cover2: "./images/flash/yerba.png",
      price: "300",
      desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
    },
    {
      id: 14,
      cover: "./images/discount/desc8.jpg",
      name: "Horno Eléctrico",
      cover1: "./images/discount/desc8.jpg",
      cover2: "./images/flash/yerba.png",
      price: "30",
      desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
    },
    {
      id: 15,
      cover: "./images/discount/desc0.jpg",
      name: "Secarropas",
      cover1: "./images/discount/desc9.jpg",
      cover2: "./images/flash/yerba.png",
      price: "80",
      desc: "Sé el primero en valorar “YERBA ORGANICA ROAPIPO SUAVE X 500 G”",
    },
  ],
};
export default Data;
