const Sdata = {
  shopItems: [
    {
      id: 16,
      cover: "./images/shops/apple22.jpg",
      name: "Apple iPhone 13 Pro Max",
      cover1: "./images/shops/apple22.jpg",
      cover2: "./images/flash/yerba.png",
      price: "300",
      discount: "20",
      cateName: "apple",
    },

    {
      id: 18,
      cover: "./images/shops/apple8.jpeg",
      name: "Apple iPhone 14 Pro Max",
      price: "80",
      discount: "15",
      cateName: "apple",
    },

    {
      id: 19,
      cover: "./images/shops/samsung2.jpg",
      name: "Samsung Galaxy A33",
      price: "20",
      discount: "50 ",
      cateName: "samsung",
    },
    {
      id: 20,
      cover: "./images/shops/redmi.jpg",
      name: "Xiaomi Redmi Note 10 Pro",
      price: "999",
      discount: "10 ",
      cateName: "redmi",
    },

    {
      id: 22,
      cover: "./images/shops/shops-7.png",
      name: "Redmi Phone",
      price: "400",
      discount: "20 ",
      cateName: "redmi",
    },
    {
      id: 23,
      cover: "./images/shops/redmi3.jpg",
      name: "Redmi 10C",
      price: "60",
      discount: "5 ",
      cateName: "redmi",
    },
    {
      id: 24,
      cover: "./images/shops/samsung1.jpg",
      name: "Samsung A52s",
      price: "180",
      discount: "10",
      cateName: "samsung",
    },
    {
      id: 25,
      cover: "./images/shops/apple3.jpg",
      name: "Apple Watch SE GPS",
      price: "5",
      discount: "2",
      cateName: "apple",
    },
    {
      id: 26,
      cover: "./images/shops/apple11.jpg",
      name: "Apple AirPods",
      price: "80",
      discount: "15",
      cateName: "apple",
    },
    {
      id: 27,
      cover: "./images/shops/apple9.jpeg",
      name: "Apple iPhone 13",
      price: "80",
      discount: "15",
      cateName: "apple",
    },
    {
      id: 28,
      cover: "./images/shops/shops-2.png",
      name: "Vivo android one",
      price: "120",
      discount: "10",
      cateName: "vivo",
    },
    {
      id: 29,
      cover: "./images/shops/opo.jpg",
      name: "OPPO A74",
      price: "120",
      discount: "10",
      cateName: "oppo",
    },
    {
      id: 21,
      cover: "./images/shops/shops-5.png",
      name: "Ceats wireless earphone",
      price: "80",
      discount: "20 ",
      cateName: "Otros",
    },
    {
      id: 17,
      cover: "./images/shops/shops-1.png",
      name: "Mapple Earphones",
      price: "180",
      discount: "25",
      cateName: "Otros",
    },
  ],
};
export default Sdata;
